import React,{useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {Activity,ArrowUpRight,Bot,CheckCircle2,CircleDollarSign,FileText,LayoutDashboard,Mail,Menu,Search,ShieldCheck,Sparkles,X} from "lucide-react";
import "./styles.css";

type Invoice={id:string;customer:string;amount:number;due:string;status:"Paid"|"Overdue"|"Pending";risk:"Low"|"Medium"|"High"};
const invoices:Invoice[]=[
{id:"INV-1042",customer:"Acme Corp",amount:480000,due:"2026-09-15",status:"Overdue",risk:"High"},
{id:"INV-1045",customer:"Northstar Labs",amount:215000,due:"2026-09-25",status:"Overdue",risk:"Medium"},
{id:"INV-1051",customer:"Orbit Systems",amount:98000,due:"2026-10-12",status:"Pending",risk:"Low"},
{id:"INV-1038",customer:"Vertex Health",amount:620000,due:"2026-09-05",status:"Overdue",risk:"High"},
{id:"INV-1049",customer:"Brightline AI",amount:126000,due:"2026-09-20",status:"Paid",risk:"Low"}
];
const agents=[["Planner","Routes finance tasks to the right specialists"],["Research Agent","Retrieves invoices, customers and policies"],["Finance Agent","Calculates exposure, aging and risk"],["Document Agent","Extracts invoice and PO fields"],["Verification Agent","Checks claims against source data"],["Editor Agent","Produces reports and follow-up actions"]] as const;
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);

function App(){
 const [section,setSection]=useState("Dashboard"); const [selected,setSelected]=useState<Invoice|null>(null); const [query,setQuery]=useState(""); const [running,setRunning]=useState(false); const [done,setDone]=useState(false); const [mail,setMail]=useState(false);
 const filtered=useMemo(()=>invoices.filter(i=>`${i.id} ${i.customer}`.toLowerCase().includes(query.toLowerCase())),[query]);
 const runWorkflow=()=>{setRunning(true);setDone(false);setTimeout(()=>{setRunning(false);setDone(true)},1400)};
 const nav=[["Dashboard",LayoutDashboard],["Invoices",FileText],["Agents",Bot],["Knowledge",Search],["Evaluations",ShieldCheck]] as const;
 return <div className="app">
  <aside className="sidebar">
   <div className="brand"><div className="brandmark"><Sparkles size={18}/></div><div><b>FinPilot</b><span>Agentic finance</span></div></div>
   <nav>{nav.map(([n,I])=><button key={n} className={section===n?"active":""} onClick={()=>setSection(n)}><I size={18}/>{n}</button>)}</nav>
   <div className="sidecard"><div className="pill"><CircleDollarSign size={15}/> Demo mode</div><p>Seeded finance data is ready to explore.</p><button onClick={runWorkflow}>Run agent demo <ArrowUpRight size={15}/></button></div>
  </aside>
  <main className="main">
   <header><div className="mobilebrand"><Menu size={20}/><b>FinPilot</b></div><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search invoices, customers…"/></div><div className="headerRight"><div className="avatar">MB</div></div></header>
   {section==="Dashboard"&&<Dashboard runWorkflow={runWorkflow} running={running} done={done} setSection={setSection} setSelected={setSelected}/>}
   {section==="Invoices"&&<Section title="Invoices" eyebrow="Receivables workspace"><div className="table big">{filtered.map(i=><InvoiceRow key={i.id} invoice={i} onClick={()=>{setSelected(i);setMail(false)}}/>)}</div></Section>}
   {section==="Agents"&&<Section title="Agents" eyebrow="Orchestration"><div className="agentgrid">{agents.map(([n,d],idx)=><div className="agentcard" key={n}><div className="agenttop"><div className="agenticon"><Bot size={17}/></div><span className="verified"><CheckCircle2 size={14}/> active</span></div><h3>{n}</h3><p>{d}</p><div className="meter"><i style={{width:`${76+(idx*3)}%`}}/></div><small>Ready for workflow execution</small></div>)}</div></Section>}
   {section==="Knowledge"&&<Section title="Knowledge base" eyebrow="RAG + citations"><div className="knowledge">{[["Collections Policy","12 sections · updated 2 days ago"],["Invoice Approval Matrix","8 sections · updated 5 days ago"],["Vendor Payment SOP","15 sections · updated 9 days ago"]].map(([t,s])=><div className="doc" key={t}><FileText size={20}/><div><b>{t}</b><span>{s}</span></div><span className="tag">indexed</span></div>)}</div></Section>}
   {section==="Evaluations"&&<Section title="Evaluation lab" eyebrow="Prompt QA"><div className="evalgrid"><Eval label="Factual accuracy" value="94.2%" delta="+12.4 pts"/><Eval label="Hallucination rate" value="3.1%" delta="-7.9 pts"/><Eval label="Tool success" value="95.4%" delta="+9.8 pts"/><Eval label="Avg latency" value="3.1s" delta="-22%"/></div><div className="card"><div className="cardHead"><div><span className="eyebrow">Prompt benchmark</span><h2>Version comparison</h2></div></div><div className="bench"><div><span>Finance Agent v1</span><strong>82.0%</strong></div><div><span>Finance Agent v2</span><strong>94.2%</strong></div><div><span>Verification v1</span><strong>91.6%</strong></div></div></div></Section>}
   {selected&&<InvoiceModal invoice={selected} mail={mail} setMail={setMail} close={()=>setSelected(null)}/>}
  </main>
 </div>
}
function Dashboard({runWorkflow,running,done,setSection,setSelected}:{runWorkflow:()=>void;running:boolean;done:boolean;setSection:(s:string)=>void;setSelected:(i:Invoice)=>void}){
 return <><section className="hero"><div><div className="eyebrow">Finance operations copilot</div><h1>Turn finance work into<br/><span>verified agent workflows.</span></h1><p>Investigate invoices, ground answers in policy, verify every claim, and draft next actions — without leaving one workspace.</p><div className="heroActions"><button className="primary" onClick={runWorkflow}><Bot size={17}/>{running?"Running agents…":"Run invoice risk analysis"}</button><button className="secondary" onClick={()=>setSection("Invoices")}>Explore invoices <ArrowUpRight size={16}/></button></div></div><div className="heroVisual"><div className="traceHead"><span>Live agent trace</span><span className="live"><i/> {running?"processing":"ready"}</span></div>{agents.slice(0,5).map(([n,d],idx)=><div className="trace" key={n}><div className="traceIcon">{running&&idx<4?<Activity size={15}/>:<CheckCircle2 size={15}/>}</div><div><b>{n}</b><span>{d}</span></div><em>{running?([220,440,660,880,1040][idx]+"ms"):"verified"}</em></div>)}{done&&<div className="success"><CheckCircle2 size={16}/>Verified workflow complete · 3 invoices need action</div>}</div></section><section className="stats"><Stat label="Outstanding" value="₹42.8L" change="+8.4%"/><Stat label="Overdue invoices" value="17" change="3 high risk"/><Stat label="Auto-verified claims" value="94.2%" change="+4.1 pts"/><Stat label="Avg. response" value="3.1s" change="-22%"/></section><section className="grid2"><div className="card"><div className="cardHead"><div><span className="eyebrow">Priority queue</span><h2>Invoices needing attention</h2></div><button className="iconbtn" onClick={()=>setSection("Invoices")}><ArrowUpRight size={16}/></button></div><div className="table">{invoices.filter(i=>i.status==="Overdue").slice(0,3).map(i=><InvoiceRow key={i.id} invoice={i} onClick={()=>setSelected(i)}/>)}</div></div><div className="card"><div className="cardHead"><div><span className="eyebrow">Knowledge grounded</span><h2>Finance policy assistant</h2></div><MessageDot/></div><div className="chat"><div className="bubble bot">According to the Collections Policy, invoices become eligible for escalation after <b>14 days overdue</b>.<small>Source · Collections Policy §3.2</small></div><div className="ask">Try a grounded query from the search bar, e.g. <b>INV-1042</b>.</div></div></div></section></>
}
function MessageDot(){return <div className="messageDot">AI</div>}
function InvoiceRow({invoice,onClick}:{invoice:Invoice;onClick:()=>void}){return <div className="row" onClick={onClick}><div><b>{invoice.id}</b><span>{invoice.customer}</span></div><div><b>{money(invoice.amount)}</b><span className={`status ${invoice.status.toLowerCase()}`}>{invoice.status}</span></div><span className={`risk ${invoice.risk.toLowerCase()}`}>{invoice.risk} risk</span><ArrowUpRight size={16}/></div>}
function InvoiceModal({invoice,mail,setMail,close}:{invoice:Invoice;mail:boolean;setMail:(v:boolean)=>void;close:()=>void}){return <div className="modalWrap" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X size={18}/></button><span className="eyebrow">Invoice investigation</span><h2>{invoice.id}</h2><p className="muted">{invoice.customer} · {money(invoice.amount)}</p><div className="detailGrid"><div><span>Risk</span><b className={`risk ${invoice.risk.toLowerCase()}`}>{invoice.risk}</b></div><div><span>Due date</span><b>{invoice.due}</b></div><div><span>Status</span><b>{invoice.status}</b></div><div><span>Evidence</span><b>18 claims checked</b></div></div><div className="verifyBox"><ShieldCheck size={20}/><div><b>Verification passed</b><p>Amount, due date, customer and payment history match source records.</p></div></div><button className="primary full" onClick={()=>setMail(true)}><Mail size={17}/>Draft follow-up email</button>{mail&&<div className="email"><div className="emailHead"><b>Draft email</b><span>AI generated · editable</span></div><p>Subject: Follow-up on {invoice.id}</p><p>Hi {invoice.customer} team,<br/><br/>Our records show {invoice.id} for {money(invoice.amount)} is currently overdue. Could you share an update on the expected payment date?<br/><br/>Thanks,<br/>Finance Operations</p></div>}</div></div>}
function Stat({label,value,change}:{label:string;value:string;change:string}){return <div className="stat"><span>{label}</span><b>{value}</b><em>{change}</em></div>}
function Eval({label,value,delta}:{label:string;value:string;delta:string}){return <div className="eval"><span>{label}</span><b>{value}</b><em>{delta}</em></div>}
function Section({title,eyebrow,children}:{title:string;eyebrow:string;children:React.ReactNode}){return <section className="page"><div className="pageHead"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div></div>{children}</section>}
createRoot(document.getElementById("root")!).render(<App/>);
